In [1]:
import numpy as np
import pandas as pd

In [2]:
df_acc = pd.read_csv(
    f'../dataset/accdata/accident2020_with_road_1.csv', parse_dates=["start", "stop"])
df = pd.read_csv(f'../dataset/2020-02-road-1-in.csv', parse_dates=["datetime"])

In [3]:
df

,datetime,road_number,km,direction,all_units,inflow_units,outflow_unit,samecell_units,avg_speed,max_speed,avg_traveltime,max_traveltime
0,2020-02-01 00:00:34,1,19,in,0,0,1,0,0,0,0,0
1,2020-02-01 00:00:34,1,26,in,1,0,0,1,71,71,0,0
2,2020-02-01 00:00:34,1,28,in,3,1,1,2,41,48,0,0
3,2020-02-01 00:00:34,1,29,in,3,3,3,0,75,108,0,0
4,2020-02-01 00:00:34,1,30,in,5,5,3,0,32,56,62,66
...,...,...,...,...,...,...,...,...,...,...,...,...
22694507,2020-02-29 23:59:14,1,939,in,1,0,0,1,20,20,0,0
22694508,2020-02-29 23:59:14,1,941,in,0,0,1,0,0,0,0,0
22694509,2020-02-29 23:59:14,1,959,in,1,1,0,0,47,47,60,60
22694510,2020-02-29 23:59:14,1,960,in,0,0,1,0,0,0,0,0
22694511,2020-02-29 23:59:14,1,968,in,1,0,0,1,65,65,0,0

In [4]:
# df_temp = df.set_index('datetime')
# df_temp.resample('5T').mean()
# df.resample('5T', on="datetime").mean()
df = df.groupby('km').resample('30T', on="datetime").mean()
df = df.dropna()
df

                         road_number     km  all_units  inflow_units  \
km  datetime
19  2020-02-01 00:00:00          1.0   19.0       0.00          0.00
    2020-02-01 00:30:00          1.0   19.0       0.00          0.00
    2020-02-01 01:00:00          1.0   19.0       0.00          0.00
    2020-02-01 01:30:00          1.0   19.0       0.00          0.00
    2020-02-01 02:00:00          1.0   19.0       0.00          0.00
...                              ...    ...        ...           ...
993 2020-02-29 18:30:00          1.0  993.0       0.80          0.20
    2020-02-29 19:00:00          1.0  993.0       0.25          0.25
    2020-02-29 19:30:00          1.0  993.0       1.00          1.00
    2020-02-29 20:30:00          1.0  993.0       0.00          0.00
    2020-02-29 21:00:00          1.0  993.0       1.00          1.00

                         outflow_unit  samecell_units  avg_speed  max_speed  \
km  datetime
19  2020-02-01 00:00:00      1.952381             0.0   0.000000        0.0
    2020-02-01 00:30:00      1.894737             0.0   0.000000        0.0
    2020-02-01 01:00:00      1.956522             0.0   0.000000        0.0
    2020-02-01 01:30:00      1.600000             0.0   0.000000        0.0
    2020-02-01 02:00:00      1.818182             0.0   0.000000        0.0
...                               ...             ...        ...        ...
993 2020-02-29 18:30:00      0.200000             0.6  11.800000       11.8
    2020-02-29 19:00:00      0.750000             0.0  15.500000       15.5
    2020-02-29 19:30:00      0.333333             0.0  38.666667       40.0
    2020-02-29 20:30:00      1.000000             0.0   0.000000        0.0
    2020-02-29 21:00:00      0.000000             0.0  44.500000       44.5

                         avg_traveltime  max_traveltime
km  datetime
19  2020-02-01 00:00:00             0.0             0.0
    2020-02-01 00:30:00             0.0             0.0
    2020-02-01 01:00:00             0.0             0.0
    2020-02-01 01:30:00             0.0             0.0
    2020-02-01 02:00:00             0.0             0.0
...                                 ...             ...
993 2020-02-29 18:30:00            16.4            16.4
    2020-02-29 19:00:00            15.0            15.0
    2020-02-29 19:30:00             0.0             0.0
    2020-02-29 20:30:00             0.0             0.0
    2020-02-29 21:00:00            34.5            34.5

[1308957 rows x 10 columns]

In [5]:
df = df.droplevel(0, axis=0)

In [6]:
df = df.reset_index()

In [7]:
df

,datetime,road_number,km,all_units,inflow_units,outflow_unit,samecell_units,avg_speed,max_speed,avg_traveltime,max_traveltime
0,2020-02-01 00:00:00,1.0,19.0,0.00,0.00,1.952381,0.0,0.000000,0.0,0.0,0.0
1,2020-02-01 00:30:00,1.0,19.0,0.00,0.00,1.894737,0.0,0.000000,0.0,0.0,0.0
2,2020-02-01 01:00:00,1.0,19.0,0.00,0.00,1.956522,0.0,0.000000,0.0,0.0,0.0
3,2020-02-01 01:30:00,1.0,19.0,0.00,0.00,1.600000,0.0,0.000000,0.0,0.0,0.0
4,2020-02-01 02:00:00,1.0,19.0,0.00,0.00,1.818182,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1308952,2020-02-29 18:30:00,1.0,993.0,0.80,0.20,0.200000,0.6,11.800000,11.8,16.4,16.4
1308953,2020-02-29 19:00:00,1.0,993.0,0.25,0.25,0.750000,0.0,15.500000,15.5,15.0,15.0
1308954,2020-02-29 19:30:00,1.0,993.0,1.00,1.00,0.333333,0.0,38.666667,40.0,0.0,0.0
1308955,2020-02-29 20:30:00,1.0,993.0,0.00,0.00,1.000000,0.0,0.000000,0.0,0.0,0.0
1308956,2020-02-29 21:00:00,1.0,993.0,1.00,1.00,0.000000,0.0,44.500000,44.5,34.5,34.5

In [8]:
df_acc

,eid,title,description,latitude,longitude,start,stop,latx,lonx,coor,road_number,km
0,645583,เปิดช่องทางพิเศษ ถนนพหลโยธิน ขาเข้า กม.101+800,เปิดช่องเดินรถพิเศษ ส่งรถเข้ากรุงเทพ \r\nแขวงท...,14.470397,100.908655,2020-01-01 16:36:54,2020-01-01 17:36:54,14.470,100.908,"14.47, 100.908",1,101
1,645816,อุบัติเหตุ เชียงราย,เกิดอุบัติเหตุ ข้อมูลจาก บริษัท กลางคุ้มครองผู...,20.113915,99.873019,2020-01-01 16:17:00,2020-01-01 17:17:00,20.113,99.873,"20.113, 99.873",1,956
2,646710,อุบัติเหตุ เมืองสระบุรี สระบุรี,เกิดอุบัติเหตุ ข้อมูลจาก บริษัท กลางคุ้มครองผู...,14.530608,100.912187,2020-01-04 17:00:00,2020-01-04 18:00:00,14.530,100.912,"14.53, 100.912",1,108
3,648559,อุบัติเหตุ ดาวเรือง เมืองสระบุรี สระบุรี,เกิดอุบัติเหตุ ข้อมูลจาก บริษัท กลางคุ้มครองผู...,14.556979,100.906328,2020-01-10 21:56:00,2020-01-10 22:56:00,14.556,100.906,"14.556, 100.906",1,111
4,648570,อุบัติเหตุ ดาวเรือง เมืองสระบุรี สระบุรี,เกิดอุบัติเหตุ ข้อมูลจาก บริษัท กลางคุ้มครองผู...,14.556965,100.906001,2020-01-10 22:30:00,2020-01-10 23:30:00,14.556,100.906,"14.556, 100.906",1,111
...,...,...,...,...,...,...,...,...,...,...,...,...
87,695332,คืบหน้ารถเสีย ถนนพหลโยธิน ขาเข้า,คืบหน้ารถจอดเสีย ถนนพหลโยธิน ขาเข้า ตรงข้าม ม...,14.069338,100.617664,2020-12-07 18:10:35,2020-12-07 19:10:35,14.069,100.617,"14.069, 100.617",1,41
88,695340,รถเสีย ถนนพหลโยธิน ขาเข้า,ถนนพหลโยธิน ขาเข้า ก่อนถึง เซียร์รังสิต เล็กน้...,13.961292,100.620541,2020-12-07 18:54:43,2020-12-07 19:54:43,13.961,100.620,"13.961, 100.62",1,29
89,696815,อุบัติเหตุ ถนนพหลโยธิน ขาออก,20:40 อุบัติเหตุ ถนนพหลโยธิน ที่บริเวณหน้าม.ธ...,14.069546,100.617433,2020-12-17 20:44:25,2020-12-17 21:44:25,14.069,100.617,"14.069, 100.617",1,41
90,698655,รถเสีย ถนนพหลโยธิน,ต.หนองไข่น้ำ อ.หนองแค จ.สระบุรี 18140,14.374261,100.882204,2020-12-30 23:05:00,2020-12-31 00:05:00,14.374,100.882,"14.374, 100.882",1,90
91,698713,อุบัติเหตุ ถนนพหลโยธิน ขาออก,ถนนพหลโยธิน ขาออก ก่อนถึง นิคมอุตสาหกรรม หนองแ...,14.374543,100.882174,2020-12-31 10:43:34,2020-12-31 11:43:34,14.374,100.882,"14.374, 100.882",1,90

In [9]:
df_new_acc = df_acc.groupby('km').resample('30T', on="start").count()
df_new_acc

                         eid  title  description  latitude  longitude  start  \
km  start
27  2020-02-18 14:30:00    1      1            1         1          1      1
    2020-02-18 15:00:00    0      0            0         0          0      0
    2020-02-18 15:30:00    0      0            0         0          0      0
    2020-02-18 16:00:00    0      0            0         0          0      0
    2020-02-18 16:30:00    0      0            0         0          0      0
...                      ...    ...          ...       ...        ...    ...
956 2020-01-01 16:00:00    1      1            1         1          1      1
983 2020-01-18 20:30:00    1      1            1         1          1      1
989 2020-01-28 09:30:00    1      1            1         1          1      1
991 2020-02-02 18:30:00    1      1            1         1          1      1
994 2020-02-16 18:00:00    1      1            1         1          1      1

                         stop  latx  lonx  coor  road_number  km
km  start
27  2020-02-18 14:30:00     1     1     1     1            1   1
    2020-02-18 15:00:00     0     0     0     0            0   0
    2020-02-18 15:30:00     0     0     0     0            0   0
    2020-02-18 16:00:00     0     0     0     0            0   0
    2020-02-18 16:30:00     0     0     0     0            0   0
...                       ...   ...   ...   ...          ...  ..
956 2020-01-01 16:00:00     1     1     1     1            1   1
983 2020-01-18 20:30:00     1     1     1     1            1   1
989 2020-01-28 09:30:00     1     1     1     1            1   1
991 2020-02-02 18:30:00     1     1     1     1            1   1
994 2020-02-16 18:00:00     1     1     1     1            1   1

[100195 rows x 12 columns]

In [10]:
df_new_acc.drop(df_new_acc[df_new_acc['km'] == 0].index, inplace=True)
df_new_acc = df_new_acc.drop(["start", "km"], axis=1).reset_index()
df_new_acc

,km,start,eid,title,description,latitude,longitude,stop,latx,lonx,coor,road_number
0,27,2020-02-18 14:30:00,1,1,1,1,1,1,1,1,1,1
1,27,2020-07-16 22:00:00,1,1,1,1,1,1,1,1,1,1
2,27,2020-10-01 19:00:00,1,1,1,1,1,1,1,1,1,1
3,27,2020-11-17 00:30:00,1,1,1,1,1,1,1,1,1,1
4,28,2020-04-26 15:00:00,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
85,956,2020-01-01 16:00:00,1,1,1,1,1,1,1,1,1,1
86,983,2020-01-18 20:30:00,1,1,1,1,1,1,1,1,1,1
87,989,2020-01-28 09:30:00,1,1,1,1,1,1,1,1,1,1
88,991,2020-02-02 18:30:00,1,1,1,1,1,1,1,1,1,1
89,994,2020-02-16 18:00:00,1,1,1,1,1,1,1,1,1,1

In [11]:
df_new_acc[(df_new_acc["start"] >= pd.Timestamp(2020, 2, 1)) & (df_new_acc["start"] <= pd.Timestamp(2020, 3, 1))]

,km,start,eid,title,description,latitude,longitude,stop,latx,lonx,coor,road_number
0,27,2020-02-18 14:30:00,1,1,1,1,1,1,1,1,1,1
14,30,2020-02-04 16:00:00,1,1,1,1,1,1,1,1,1,1
28,41,2020-02-26 15:00:00,1,1,1,1,1,1,1,1,1,1
38,42,2020-02-14 11:00:00,1,1,1,1,1,1,1,1,1,1
42,47,2020-02-10 21:30:00,1,1,1,1,1,1,1,1,1,1
58,94,2020-02-15 13:30:00,1,1,1,1,1,1,1,1,1,1
62,98,2020-02-23 10:00:00,1,1,1,1,1,1,1,1,1,1
68,121,2020-02-13 07:00:00,1,1,1,1,1,1,1,1,1,1
72,280,2020-02-18 02:00:00,1,1,1,1,1,1,1,1,1,1
75,697,2020-02-21 16:00:00,1,1,1,1,1,1,1,1,1,1
84,881,2020-02-03 10:30:00,1,1,1,1,1,1,1,1,1,1
88,991,2020-02-02 18:30:00,1,1,1,1,1,1,1,1,1,1
89,994,2020-02-16 18:00:00,1,1,1,1,1,1,1,1,1,1

In [12]:
df

,datetime,road_number,km,all_units,inflow_units,outflow_unit,samecell_units,avg_speed,max_speed,avg_traveltime,max_traveltime
0,2020-02-01 00:00:00,1.0,19.0,0.00,0.00,1.952381,0.0,0.000000,0.0,0.0,0.0
1,2020-02-01 00:30:00,1.0,19.0,0.00,0.00,1.894737,0.0,0.000000,0.0,0.0,0.0
2,2020-02-01 01:00:00,1.0,19.0,0.00,0.00,1.956522,0.0,0.000000,0.0,0.0,0.0
3,2020-02-01 01:30:00,1.0,19.0,0.00,0.00,1.600000,0.0,0.000000,0.0,0.0,0.0
4,2020-02-01 02:00:00,1.0,19.0,0.00,0.00,1.818182,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1308952,2020-02-29 18:30:00,1.0,993.0,0.80,0.20,0.200000,0.6,11.800000,11.8,16.4,16.4
1308953,2020-02-29 19:00:00,1.0,993.0,0.25,0.25,0.750000,0.0,15.500000,15.5,15.0,15.0
1308954,2020-02-29 19:30:00,1.0,993.0,1.00,1.00,0.333333,0.0,38.666667,40.0,0.0,0.0
1308955,2020-02-29 20:30:00,1.0,993.0,0.00,0.00,1.000000,0.0,0.000000,0.0,0.0,0.0
1308956,2020-02-29 21:00:00,1.0,993.0,1.00,1.00,0.000000,0.0,44.500000,44.5,34.5,34.5

In [13]:
li1 = df_new_acc["start"].tolist()
li2 = df_new_acc["km"].tolist()
for i in range(len(df)):
    if(df.loc[i, "datetime"] in li1) and (df.loc[i, "km"] in li2):
        print(df.loc[i])

datetime          2020-02-02 18:30:00
road_number                       1.0
km                               27.0
all_units                    3.310345
inflow_units                 2.862069
outflow_unit                 2.517241
samecell_units               0.448276
avg_speed                   41.793103
max_speed                   56.551724
avg_traveltime               62.37931
max_traveltime              79.413793
Name: 4261, dtype: object
datetime          2020-02-03 10:30:00
road_number                       1.0
km                               27.0
all_units                    3.517241
inflow_units                 2.896552
outflow_unit                 1.827586
samecell_units                0.62069
avg_speed                   45.344828
max_speed                    65.62069
avg_traveltime              59.896552
max_traveltime              71.034483
Name: 4293, dtype: object
datetime          2020-02-04 16:00:00
road_number                       1.0
km                               27.0
all_units                    3.724138
inflow_units                 3.241379
outflow_unit                 2.655172
samecell_units               0.482759
avg_speed                   43.931034
max_speed                   64.689655
avg_traveltime              62.793103
max_traveltime              67.655172
Name: 4352, dtype: object
datetime          2020-02-10 21:30:00
road_number                       1.0
km                               27.0
all_units                    2.777778
inflow_units                 2.222222
outflow_unit                 1.814815
samecell_units               0.555556
avg_speed                   47.814815
max_speed                   62.481481
avg_traveltime              50.333333
max_traveltime              60.740741
Name: 4651, dtype: object
datetime          2020-02-13 07:00:00
road_number                       1.0
km                               27.0
all_units                    2.533333
inflow_units                 2.033333
outflow_unit                      1.5
samecell_units                    0.5
avg_speed                   35.733333
max_speed                        50.5
avg_traveltime              55.733333
max_traveltime              64.133333
Name: 4766, dtype: object
datetime          2020-02-14 11:00:00
road_number                       1.0
km                               27.0
all_units                         4.1
inflow_units                 3.566667
outflow_unit                      2.4
samecell_units               0.533333
avg_speed                   43.333333
max_speed                   61.466667
avg_traveltime                   70.6
max_traveltime                   92.5
Name: 4822, dtype: object
datetime          2020-02-15 13:30:00
road_number                       1.0
km                               27.0
all_units                    4.133333
inflow_units                 3.566667
outflow_unit                      2.8
samecell_units               0.566667
avg_speed                   46.633333
max_speed                   65.733333
avg_traveltime              67.066667
max_traveltime                   81.6
Name: 4875, dtype: object
datetime          2020-02-16 18:00:00
road_number                       1.0
km                               27.0
all_units                    3.033333
inflow_units                 2.566667
outflow_unit                 2.166667
samecell_units               0.466667
avg_speed                        45.3
max_speed                        61.4
avg_traveltime                   57.4
max_traveltime                   65.8
Name: 4932, dtype: object
datetime          2020-02-18 02:00:00
road_number                       1.0
km                               27.0
all_units                    1.458333
inflow_units                    1.375
outflow_unit                    1.125
samecell_units               0.083333
avg_speed                   46.666667
max_speed                   51.458333
avg_traveltime                 42.875
max_traveltime              44.541667
Name: 4996, dtype: object
datetime          2020-02-18 14:30:00
road_number                       1.0
km                               27.0
all_units                         3.9
inflow_units                 2.966667
outflow_unit                      2.5
samecell_units               0.933333
avg_speed                   42.566667
max_speed                   64.433333
avg_traveltime              61.133333
max_traveltime              72.566667
Name: 5021, dtype: object
datetime          2020-02-21 16:00:00
road_number                       1.0
km                               27.0
all_units                    3.137931
inflow_units                 2.586207
outflow_unit                 2.448276
samecell_units               0.551724
avg_speed                    41.37931
max_speed                   58.586207
avg_traveltime              59.310345
max_traveltime               70.62069
Name: 5168, dtype: object
datetime          2020-02-23 10:00:00
road_number                       1.0
km                               27.0
all_units                    3.766667
inflow_units                 3.166667
outflow_unit                      2.6
samecell_units                    0.6
avg_speed                        44.1
max_speed                        65.0
avg_traveltime              54.233333
max_traveltime                   66.2
Name: 5252, dtype: object
datetime          2020-02-26 15:00:00
road_number                       1.0
km                               27.0
all_units                    3.533333
inflow_units                 3.033333
outflow_unit                      2.7
samecell_units                    0.5
avg_speed                   45.966667
max_speed                        62.3
avg_traveltime                   62.3
max_traveltime              79.233333
Name: 5406, dtype: object
datetime          2020-02-02 18:30:00
road_number                       1.0
km                               28.0
all_units                         9.6
inflow_units                      6.5
outflow_unit                 6.033333
samecell_units                    3.1
avg_speed                        34.9
max_speed                        63.0
avg_traveltime              58.866667
max_traveltime                   74.2
Name: 5653, dtype: object
datetime          2020-02-03 10:30:00
road_number                       1.0
km                               28.0
all_units                   14.866667
inflow_units                      7.7
outflow_unit                 7.266667
samecell_units               7.166667
avg_speed                   22.733333
max_speed                   59.033333
avg_traveltime              67.033333
max_traveltime                   78.3
Name: 5685, dtype: object
datetime          2020-02-04 16:00:00
road_number                       1.0
km                               28.0
all_units                         8.9
inflow_units                 6.433333
outflow_unit                 5.433333
samecell_units               2.466667
avg_speed                   36.766667
max_speed                        65.6
avg_traveltime                   60.8
max_traveltime              76.533333
Name: 5744, dtype: object
datetime          2020-02-10 21:30:00
road_number                       1.0
km                               28.0
all_units                    6.666667
inflow_units                      5.3
outflow_unit                      4.7
samecell_units               1.366667
avg_speed                   45.533333
max_speed                   68.666667
avg_traveltime              60.333333
max_traveltime                   71.6
Name: 6043, dtype: object
datetime          2020-02-13 07:00:00
road_number                       1.0
km                               28.0
all_units                   16.933333
inflow_units                      5.6
outflow_unit                 5.566667
samecell_units              11.333333
avg_speed                   15.033333
max_speed                        58.3
avg_traveltime              52.266667
max_traveltime                   58.1
Name: 6158, dtype: object
datetime          2020-02-14 11:00:00
road_number                       1.0
km                               28.0
all_units                        14.9
inflow_units                 8.666667
outflow_unit                 6.166667
samecell_units               6.233333
avg_speed                   26.266667
max_speed                   59.266667
avg_traveltime              69.166667
max_traveltime              89.633333
Name: 6214, dtype: object
datetime          2020-02-15 13:30:00
road_number                       1.0
km                               28.0
all_units                    9.033333
inflow_units                 6.833333
outflow_unit                      6.0
samecell_units                    2.2
avg_speed                   38.366667
max_speed                   62.033333
avg_traveltime              51.633333
max_traveltime              63.766667
Name: 6267, dtype: object
datetime          2020-02-16 18:00:00
road_number                       1.0
km                               28.0
all_units                    7.966667
inflow_units                 6.266667
outflow_unit                 5.666667
samecell_units                    1.7
avg_speed                   42.033333
max_speed                        65.4
avg_traveltime              40.166667
max_traveltime              45.733333
Name: 6324, dtype: object
datetime          2020-02-18 02:00:00
road_number                       1.0
km                               28.0
all_units                         2.8
inflow_units                 2.333333
outflow_unit                      2.6
samecell_units               0.466667
avg_speed                   46.166667
max_speed                   58.133333
avg_traveltime                   35.7
max_traveltime                   40.9
Name: 6388, dtype: object
datetime          2020-02-18 14:30:00
road_number                       1.0
km                               28.0
all_units                    7.866667
inflow_units                 6.066667
outflow_unit                 5.033333
samecell_units                    1.8
avg_speed                   39.966667
max_speed                   65.366667
avg_traveltime                   65.8
max_traveltime                   79.6
Name: 6413, dtype: object
datetime          2020-02-21 16:00:00
road_number                       1.0
km                               28.0
all_units                         8.4
inflow_units                 6.066667
outflow_unit                 5.733333
samecell_units               2.333333
avg_speed                        35.1
max_speed                   60.833333
avg_traveltime                   58.6
max_traveltime              69.133333
Name: 6560, dtype: object
datetime          2020-02-23 10:00:00
road_number                       1.0
km                               28.0
all_units                         7.3
inflow_units                 5.366667
outflow_unit                      5.4
samecell_units               1.933333
avg_speed                        38.0
max_speed                   63.933333
avg_traveltime              60.133333
max_traveltime              87.366667
Name: 6644, dtype: object
datetime          2020-02-26 15:00:00
road_number                       1.0
km                               28.0
all_units                    7.733333
inflow_units                      6.3
outflow_unit                 5.366667
samecell_units               1.433333
avg_speed                   39.733333
max_speed                        64.1
avg_traveltime                   68.8
max_traveltime              81.966667
Name: 6798, dtype: object
datetime          2020-02-02 18:30:00
road_number                       1.0
km                               29.0
all_units                        11.3
inflow_units                      9.2
outflow_unit                 7.333333
samecell_units                    2.1
avg_speed                        37.6
max_speed                   82.033333
avg_traveltime                   72.7
max_traveltime              88.066667
Name: 7045, dtype: object
datetime          2020-02-03 10:30:00
road_number                       1.0
km                               29.0
all_units                   11.066667
inflow_units                 9.566667
outflow_unit                      6.9
samecell_units                    1.5
avg_speed                   40.066667
max_speed                   81.366667
avg_traveltime              66.666667
max_traveltime              99.333333
Name: 7077, dtype: object
datetime          2020-02-04 16:00:00
road_number                       1.0
km                               29.0
all_units                   12.666667
inflow_units                 9.433333
outflow_unit                 6.233333
samecell_units               3.233333
avg_speed                   29.966667
max_speed                   82.033333
avg_traveltime                   74.6
max_traveltime                  100.8
Name: 7136, dtype: object
datetime          2020-02-10 21:30:00
road_number                       1.0
km                               29.0
all_units                    8.033333
inflow_units                 6.666667
outflow_unit                 5.266667
samecell_units               1.366667
avg_speed                   43.933333
max_speed                        77.9
avg_traveltime              56.866667
max_traveltime                   66.8
Name: 7435, dtype: object
datetime          2020-02-13 07:00:00
road_number                       1.0
km                               29.0
all_units                   10.033333
inflow_units                 7.433333
outflow_unit                 5.166667
samecell_units                    2.6
avg_speed                   33.633333
max_speed                   79.033333
avg_traveltime              67.166667
max_traveltime              76.966667
Name: 7550, dtype: object
datetime          2020-02-14 11:00:00
road_number                       1.0
km                               29.0
all_units                   13.033333
inflow_units                11.166667
outflow_unit                      7.9
samecell_units               1.866667
avg_speed                   34.566667
max_speed                        81.0
avg_traveltime                   82.2
max_traveltime             115.133333
Name: 7606, dtype: object
datetime          2020-02-15 13:30:00
road_number                       1.0
km                               29.0
all_units                        14.3
inflow_units                     11.0
outflow_unit                      8.6
samecell_units                    3.3
avg_speed                   29.766667
max_speed                   73.966667
avg_traveltime              71.766667
max_traveltime                   95.9
Name: 7659, dtype: object
datetime          2020-02-16 18:00:00
road_number                       1.0
km                               29.0
all_units                    9.833333
inflow_units                      7.9
outflow_unit                 6.166667
samecell_units               1.933333
avg_speed                   38.566667
max_speed                   81.733333
avg_traveltime              65.166667
max_traveltime                   76.9
Name: 7716, dtype: object
datetime          2020-02-18 02:00:00
road_number                       1.0
km                               29.0
all_units                    3.666667
inflow_units                 3.259259
outflow_unit                      2.0
samecell_units               0.407407
avg_speed                   50.407407
max_speed                   68.592593
avg_traveltime              53.407407
max_traveltime              55.407407
Name: 7780, dtype: object
datetime          2020-02-18 14:30:00
road_number                       1.0
km                               29.0
all_units                        11.4
inflow_units                 9.333333
outflow_unit                 6.733333
samecell_units               2.066667
avg_speed                   34.533333
max_speed                   81.666667
avg_traveltime              77.633333
max_traveltime             106.766667
Name: 7805, dtype: object
datetime          2020-02-21 16:00:00
road_number                       1.0
km                               29.0
all_units                        12.1
inflow_units                 9.033333
outflow_unit                      7.1
samecell_units               3.066667
avg_speed                   31.933333
max_speed                   81.433333
avg_traveltime              73.566667
max_traveltime             101.333333
Name: 7952, dtype: object
datetime          2020-02-23 10:00:00
road_number                       1.0
km                               29.0
all_units                   10.933333
inflow_units                      9.1
outflow_unit                      6.5
samecell_units               1.833333
avg_speed                        37.7
max_speed                        79.3
avg_traveltime                   69.6
max_traveltime              86.233333
Name: 8036, dtype: object
datetime          2020-02-26 15:00:00
road_number                       1.0
km                               29.0
all_units                   11.033333
inflow_units                 8.533333
outflow_unit                      6.3
samecell_units                    2.5
avg_speed                   31.166667
max_speed                        75.0
avg_traveltime              70.633333
max_traveltime                   87.0
Name: 8190, dtype: object
datetime          2020-02-02 18:30:00
road_number                       1.0
km                               30.0
all_units                    9.766667
inflow_units                 8.466667
outflow_unit                 6.933333
samecell_units                    1.3
avg_speed                   40.733333
max_speed                   77.266667
avg_traveltime                   61.0
max_traveltime              71.433333
Name: 8437, dtype: object
datetime          2020-02-03 10:30:00
road_number                       1.0
km                               30.0
all_units                    9.366667
inflow_units                 8.466667
outflow_unit                 7.566667
samecell_units                    0.9
avg_speed                   49.333333
max_speed                   82.766667
avg_traveltime                   60.6
max_traveltime                   72.4
Name: 8469, dtype: object
datetime          2020-02-04 16:00:00
road_number                       1.0
km                               30.0
all_units                   10.733333
inflow_units                 9.133333
outflow_unit                 8.133333
samecell_units                    1.6
avg_speed                        40.4
max_speed                   84.966667
avg_traveltime              58.766667
max_traveltime              70.033333
Name: 8528, dtype: object
datetime          2020-02-10 21:30:00
road_number                       1.0
km                               30.0
all_units                         7.9
inflow_units                 7.133333
outflow_unit                      5.6
samecell_units               0.766667
avg_speed                   49.366667
max_speed                   81.966667
avg_traveltime              64.733333
max_traveltime                   77.2
Name: 8827, dtype: object
datetime          2020-02-13 07:00:00
road_number                       1.0
km                               30.0
all_units                    8.133333
inflow_units                 7.233333
outflow_unit                 5.533333
samecell_units                    0.9
avg_speed                   45.966667
max_speed                   84.866667
avg_traveltime              52.166667
max_traveltime              60.266667
Name: 8942, dtype: object
datetime          2020-02-14 11:00:00
road_number                       1.0
km                               30.0
all_units                   10.766667
inflow_units                      9.6
outflow_unit                 8.933333
samecell_units               1.166667
avg_speed                   45.933333
max_speed                        82.1
avg_traveltime              62.166667
max_traveltime              72.266667
Name: 8998, dtype: object

In [ ]:
for i in range(len(df)):
    for j in range(len(df_new_acc)):
        if(df['datetime'][i] == df_new_acc['start'][j]) & (df['km'][i] == df_new_acc['km'][j]):
            print(df['datetime'][i])

In [ ]:
df["isAcc"] = np.where((df["datetime"] == df_new_acc["start"])
                       and (df["km"] == df_new_acc["km"]), 1, 0)
df

In [ ]:
def checkIsAcc(df, df_acc):
    for index, row in df_acc.iterrows():
        print(df[(df['km'] == row['km']) & (df['datetime'] == row['start'])])

In [ ]:
checkIsAcc(df, df_new_acc)

                datetime  road_number    km  all_units  inflow_units  \
5021 2020-02-18 14:30:00          1.0  27.0        3.9      2.966667

      outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
5021           2.5        0.933333  42.566667  64.433333       61.133333

      max_traveltime
5021       72.566667
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                datetime  road_number    km  all_units  inflow_units  \
8528 2020-02-04 16:00:00          1.0  30.0  10.733333      9.133333

      outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
8528      8.133333             1.6       40.4  84.966667       58.766667

      max_traveltime
8528       70.033333
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                 datetime  road_number    km  all_units  inflow_units  \
24894 2020-02-26 15:00:00          1.0  41.0  15.266667     10.133333

       outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
24894           9.7        5.133333       45.4  84.766667            60.3

       max_traveltime
24894            94.2
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                 datetime  road_number    km  all_units  inflow_units  \
25702 2020-02-14 11:00:00          1.0  42.0  13.433333     10.466667

       outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
25702     10.533333        2.966667  50.566667  81.766667       59.966667

       max_traveltime
25702       92.166667
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                 datetime  road_number    km  all_units  inflow_units  \
32491 2020-02-10 21:30:00          1.0  47.0   5.033333           4.8

       outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
32491      4.933333        0.233333  56.466667  74.866667       53.366667

       max_traveltime
32491       68.366667
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                 datetime  road_number    km  all_units  inflow_units  \
98139 2020-02-15 13:30:00          1.0  94.0  12.933333          11.8

       outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
98139     11.666667        1.133333  60.666667  82.166667            57.6

       max_traveltime
98139            84.8
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                  datetime  road_number    km  all_units  inflow_units  \
104084 2020-02-23 10:00:00          1.0  98.0        8.5           4.8

        outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
104084           3.6             3.7       33.8  69.866667            56.0

        max_traveltime
104084       79.966667
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                  datetime  road_number     km  all_units  inflow_units  \
135593 2020-02-13 07:00:00          1.0  121.0       11.1      8.133333

        outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
135593      6.433333        2.966667  51.733333       79.7       48.466667

        max_traveltime
135593       73.233333
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                  datetime  road_number     km  all_units  inflow_units  \
350808 2020-02-18 02:00:00          1.0  280.0   0.666667      0.666667

        outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
350808      0.333333             0.0  40.666667  40.666667            36.0

        max_traveltime
350808            36.0
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                  datetime  road_number     km  all_units  inflow_units  \
930310 2020-02-21 16:00:00          1.0  697.0   2.464286      1.714286

        outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
930310      0.714286            0.75  25.785714  37.785714       54.464286

        max_traveltime
930310       60.571429
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                   datetime  road_number     km  all_units  inflow_units  \
1166442 2020-02-03 10:30:00          1.0  881.0       1.25           1.0

         outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
1166442          0.85            0.25       45.9      48.65            33.3

         max_traveltime
1166442            38.1
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []
                   datetime  road_number     km  all_units  inflow_units  \
1305831 2020-02-02 18:30:00          1.0  991.0        1.0          0.25

         outflow_unit  samecell_units  avg_speed  max_speed  avg_traveltime  \
1305831      0.166667            0.75       31.0  31.916667       17.083333

         max_traveltime
1305831       17.083333
Empty DataFrame
Columns: [datetime, road_number, km, all_units, inflow_units, outflow_unit, samecell_units, avg_speed, max_speed, avg_traveltime, max_traveltime]
Index: []

In [ ]:
num_cols = ['all_units', 'inflow_units',
            'avg_speed', 'max_speed',
            'avg_traveltime', 'max_traveltime']
num_cols

In [ ]:
import joblib
dtree_model = joblib.load(f'../Models/DecisionTreeModelRoad1in.joblib')
dtree_model

In [ ]:
x_predict = df[num_cols]
x_predict

In [ ]:
y_predict = dtree_model.predict(x_predict)
y_predict

In [ ]:
df["cluster"] = y_predict
df

In [ ]:
df["label"] = df.apply(
    lambda row: 1 if (row["cluster"] == 1 or row["cluster"] == 2) else 0, axis=1)
df

In [ ]:
df[df['label'] == 1]